services:
  # Backend Service
  - type: web
    name: rateflix-backend
    env: node
    plan: free
    rootDir: backend
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: PORT
        value: 5000
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: EMAIL_USER
        sync: false
      - key: EMAIL_PASS
        sync: false

# Frontend Service
staticSites:
  - name: rateflix-frontend
    env: static
    plan: free
    rootDir: frontend
    buildCommand: npm install && npm run build
    publishDir: dist
    envVars:
      - key: VITE_API_URL
        sync: false
